- name: Add pip
  become: yes
  become_user: root
  become_method: sudo
  apt:
      name: python3-pip

- name: Add Docker GPG apt Key
  become: yes
  become_user: root
  become_method: sudo
  apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

- name: Add Docker Repository
  become: yes
  become_user: root
  become_method: sudo
  apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present

- name: Update apt and install docker-ce
  become: yes
  become_user: root
  become_method: sudo
  apt:
      name: docker-ce
      state: present
      update_cache: true

- name: Install Docker Module for Python
  become: yes
  become_user: root
  become_method: sudo
  pip:
      name: docker
