- name: Deploy docker for coin plugin
  become: yes
  become_user: root
  become_method: sudo
  docker_container:
    name: '{{ container_name }}'
    image: '{{ chain_plugin_image }}:{{ chain_plugin_version }}'
    log_driver: json-file
    log_options:
      max-size: 100m
      max-file: 1
    state: started
    restart: yes
    restart_policy: always
    command: '{{ plugin_run }}'
    env:
      ENV_PROXY: '{{ chain_plugin_proxy }}'
      ENV_CONTRACT: '{{ wallet_plugin_contract }}'
      ENV_COIN_NET: '{{ coin_net }}'
      ENV_COIN_TYPE: '{{ wallet_plugin_env_coin_type }}'
      ENV_COIN_LOCAL_API: '{{ wallet_plugin_env_coin_local_api }}'
      ENV_COIN_PUBLIC_API: '{{ wallet_plugin_env_coin_public_api }}'
      ENV_POSITION: '{{ wallet_plugin_env_coin_position }}'
      ENV_WAN_IP: '{{ wallet_plugin_env_coin_wan_ip }}'
      ENV_SYNC_INTERVAL: ''
      ENV_CHAIN_ID: '{{ chain_id }}'
      ENV_LOG_DIR: '{{ chain_log_dir }}'
      ENV_CHAIN_NICKNAME: '{{ chain_nickname }}'
      ALL_PROXY: '{{ all_proxy }}'
    etc_hosts: '{{ chain_plugin_proxy_hosts | default({}) }}'
