- name: Deploy docker for chia plugin
  import_role:
    name: chain-plugin
  vars:
    container_name: chia-plugin-{{ target_environment }}
    wallet_plugin_contract: ''
    wallet_plugin_env_coin_type: chia
    wallet_plugin_env_coin_local_api: '{{ ansible_default_ipv4.address }}:{{ chia_coin_net_port }}'
    wallet_plugin_env_coin_public_api: ''
    plugin_run: 'run'
    chain_plugin_image: '{{ chia_plugin_image }}'
    chain_plugin_version: '{{ chia_plugin_version }}'
