- name: Detect golang version
  environment:
    PATH: "{{ go_bin_dir }}:{{ lookup('env', 'PATH') }}"
  shell: 'go version | grep {{ go_version }}'
  register: go_version_detect
  ignore_errors: true

- name: Print go detected version
  debug: var=go_version_detect.stdout_lines

- name: Remove old go source dir
  become: yes
  file:
    path: '{{ lookup("env","HOME") }}/go'
    state: absent
  when: go_version_detect.failed

- name: Archive go tar.gz
  become: yes
  unarchive:
    src: 'https://dl.google.com/go/go{{ go_version }}.linux-amd64.tar.gz'
    dest: '{{ lookup("env","HOME") }}'
    remote_src: yes
  when: go_version_detect.failed
