- name: Get rpcauthtoken
  become: yes
  become_user: root
  become_method: sudo
  shell: 'cat {{ vars_dir }}/{{ rpc_token_file }}.{{ ansible_default_ipv4.address }}'
  register: token

- name: Deploy docker for ironfish plugin
  import_role:
    name: chain-plugin
  vars:
    container_name: ironfish-plugin-{{ target_environment }}
    wallet_plugin_contract: ''
    wallet_plugin_env_coin_type: ironfish
    wallet_plugin_env_coin_local_api: '{{ ansible_default_ipv4.address }}:8020|{{ token.stdout }}'
    wallet_plugin_env_coin_public_api: ''
    plugin_run: 'run'
    chain_plugin_image: '{{ ironfish_plugin_image }}'
    chain_plugin_version: '{{ ironfish_plugin_version }}'
    chain_id: '{{ ironfish_chain_id | default("") }}'
    chain_nickname: '{{ ironfish_chain_nickname | default("") }}'
