- name: Deploy docker for ironfish plugin
  import_role:
    name: chain-plugin
  vars:
    container_name: ironfish-plugin-{{ target_environment }}
    wallet_plugin_contract: ''
    wallet_plugin_env_coin_type: ironfish
    wallet_plugin_env_coin_local_api: 'http://{{ ansible_default_ipv4.address }}:8020 | {{ token }}'
    wallet_plugin_env_coin_public_api: ''
    plugin_run: 'run'
