- name: Deploy docker for aleo plugin
  import_role:
    name: chain-plugin
  vars:
    container_name: aleo-plugin-{{ target_environment }}
    wallet_plugin_contract: ''
    wallet_plugin_env_coin_type: aleo
    wallet_plugin_env_coin_local_api: 'http://{{ ansible_default_ipv4.address }}:3030'
    wallet_plugin_env_coin_public_api: ''
    plugin_run: 'plugin run'
