- name: Deploy docker for spacemesh plugin
  import_role:
    name: chain-plugin
  vars:
    container_name: spacemesh-plugin-{{ target_environment }}
    wallet_plugin_contract: ''
    wallet_plugin_env_coin_type: spacemesh
    wallet_plugin_env_coin_local_api: '{{ ansible_default_ipv4.address }}:9092'
    wallet_plugin_env_coin_public_api: ''
    plugin_run: 'run'
