- name: Print home directory
  debug: var=source_dir

- name: Print output directory
  debug: var=output_dir

- name: Print inventory directory
  debug: var=inventory_dir

- name: Create output directory
  ansible.builtin.file:
    path: '{{ output_dir }}'
    state: directory
    recurse: yes
  delegate_to: 127.0.0.1

- name: Create output directory
  ansible.builtin.file:
    path: '{{ output_dir }}'
    state: directory
    recurse: yes

- name: Create log directory
  ansible.builtin.file:
    path: '{{ log_dir }}'
    state: directory
    recurse: yes
  delegate_to: 127.0.0.1

- name: Create log directory
  ansible.builtin.file:
    path: '{{ log_dir }}'
    state: directory
    recurse: yes

- name: Create host vars directory
  ansible.builtin.file:
    path: '{{ inventory_dir }}/host_vars'
    state: directory
    recurse: yes
  delegate_to: 127.0.0.1
